# CoPAI Platform
# https://copai.community
#
# Developed by Murbit GmbH as part of the Erasmus+ project:
#
# Community of Practice AI
# Project No.: 2023-2-AT01-KA210-VET-000169864
#
# Funded by the European Union. Views and opinions expressed are however
# those of the author(s) only and do not necessarily reflect those of the
# European Union or the European Education and Culture Executive Agency (EACEA).
# Neither the European Union nor EACEA can be held responsible for them.
#
# Copyright (c) 2025 Murbit GmbH
#
# Licensed under the MIT License.
# See LICENSE file for details.

FROM nginx:alpine

ARG MOODLE_GIT_BRANCH=MOODLE_403_STABLE

LABEL maintainer="Maximilian Raidl"

RUN apk add --no-cache git

# 2. Configs kopieren
RUN rm /etc/nginx/conf.d/default.conf
#COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/templates/default.conf.template

# 3. Moodle herunterladen
WORKDIR /var/www/html
RUN rm -rf /var/www/html/*
RUN git clone --depth=1 -b ${MOODLE_GIT_BRANCH} https://github.com/moodle/moodle.git .

# (Optional: Git wieder löschen, um Platz zu sparen)
RUN apk del git