# CoPAI Platform
# https://copai.community
#
# Developed by Murbit GmbH as part of the Erasmus+ project:
#
# Community of Practice AI
# Project No.: KA210-VET-4603C73C
#
# Funded by the European Union. Views and opinions expressed are however
# those of the author(s) only and do not necessarily reflect those of the
# European Union or the European Education and Culture Executive Agency (EACEA).
# Neither the European Union nor EACEA can be held responsible for them.
#
# Copyright (c) 2025 Murbit GmbH
#
# Licensed under the MIT License.
# See LICENSE file for details.

FROM nginx:alpine

# envsubst lives here in alpine
RUN apk add --no-cache gettext

# The official entrypoint auto-renders *.template files in /etc/nginx/templates/
COPY nginx.conf /etc/nginx/templates/default.conf.template
