FROM nginx:alpine

# envsubst lives here in alpine
RUN apk add --no-cache gettext

# The official entrypoint auto-renders *.template files in /etc/nginx/templates/
COPY nginx.conf /etc/nginx/templates/default.conf.template
